name = "MimeticFEM"
uuid = "126e3871-de10-4940-9d8e-7d36bf127749"
authors = ["Artur Palha"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
